#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	PLUGIN_NAME".vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	PLUGIN_NAME" VST3 (64Bit)"
#else
#define stringFileDescription	PLUGIN_NAME" VST3"
#endif
#define stringCompanyName		"Steinberg Media Technologies GmbH\0"
#define stringLegalCopyright	"Copyright(c) 2022 Steinberg Media Technologies GmbH."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
