//------------------------------------------------------------------------
// Copyright(c) 2025 FahlGrahn.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"SingularityInstrument.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"SingularityInstrument VST3 (64Bit)"
#else
#define stringFileDescription	"SingularityInstrument VST3"
#endif
#define stringCompanyName		"FahlGrahn\0"
#define stringLegalCopyright	"Copyright(c) 2025 FahlGrahn."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
