# embed_resources.cmake
# Generates a C++ header with resources embedded as byte arrays.
#
# Required variables (pass via -D):
#   RESOURCE_FILES  - semicolon-separated list of file paths
#   RESOURCE_NAMES  - semicolon-separated list of output names (1:1 with files)
#   OUTPUT_FILE     - path to write the generated .h
#   NAMESPACE       - C++ namespace to wrap the data in
#
# Optional:
#   GENERATE_IMAGE_REGISTER - if "ON", appends a singularity_register_images() template

cmake_policy(SET CMP0057 NEW)

set(output "// Auto-generated by singularity - do not edit\n#pragma once\n#include <cstdint>\n\n")
string(APPEND output "namespace ${NAMESPACE} {\n\n")

# For data resources, emit a helper struct
if(NOT GENERATE_IMAGE_REGISTER STREQUAL "ON")
    string(APPEND output "struct EmbeddedResource {\n    const uint8_t* data;\n    const int size;\n};\n\n")
endif()

foreach(res_file res_name IN ZIP_LISTS RESOURCE_FILES RESOURCE_NAMES)
    file(READ "${res_file}" content HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," content "${content}")
    string(MAKE_C_IDENTIFIER "${res_name}" var_name)
    string(APPEND output "static const uint8_t ${var_name}_data[] = {\n    ${content}\n};\n")

    if(GENERATE_IMAGE_REGISTER STREQUAL "ON")
        string(APPEND output "static const int ${var_name}_size = static_cast<int>(sizeof(${var_name}_data));\n\n")
    else()
        string(APPEND output "static const EmbeddedResource ${var_name} = { ${var_name}_data, static_cast<int>(sizeof(${var_name}_data)) };\n\n")
    endif()
endforeach()

string(APPEND output "} // namespace ${NAMESPACE}\n\n")

# Optionally generate a register helper for image resources
if(GENERATE_IMAGE_REGISTER STREQUAL "ON")
    set(image_exts ".png;.jpg;.jpeg;.gif;.bmp;.webp;.tga;.tif;.tiff")
    string(APPEND output "template<typename T>\ninline void singularity_register_images(T* target) {\n")
    foreach(res_name IN LISTS RESOURCE_NAMES)
        cmake_path(GET res_name EXTENSION LAST_ONLY ext)
        string(TOLOWER "${ext}" ext_lower)
        list(FIND image_exts "${ext_lower}" _idx)
        if(_idx GREATER -1)
            string(MAKE_C_IDENTIFIER "${res_name}" var_name)
            string(APPEND output "    target->registerImage(\"${res_name}\", ${NAMESPACE}::${var_name}_data, ${NAMESPACE}::${var_name}_size);\n")
        endif()
    endforeach()
    string(APPEND output "}\n")
endif()

file(WRITE "${OUTPUT_FILE}" "${output}")
